# Node.js
# Build a general Node.js project with yarn.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "vs2017-win2016"

steps:
  - powershell: yarn bootstrap
    displayName: "Install dependencies & compile packages"

  # - powershell: yarn lint
  #   displayName: "Run code linters"

  - powershell: yarn jest --detectLeaks --logHeapUsage --runInBand
    displayName: "Run tests"
    env:
      GENERATE_JEST_REPORT: true

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "**junit*.xml"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage results"
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: "cobertura"
      summaryFileLocation: "**/coverage/cobertura-coverage.xml"
